/// The shared component tree for the example app, written in dartx.
///
/// The exact same code renders on the server (`server.dart` -> HTML) and on the
/// client (`main.dart` -> hydrated, interactive DOM). That is the whole pitch:
/// write components once, get SSR + a live client, all in pure Dart.
///
/// This is a `.dartx` file: ordinary Dart, plus markup wherever an expression
/// is allowed. `dart run build_runner build` compiles it to `app.dartx.dart`.
library;

import 'package:reactx/events.dart';
import 'package:reactx/reactx.dart';

/// Root component.
Component App() => h('div', <String, Object?>{'class': 'app'}, <Object?>[
h('h1', const <String, Object?>{}, <Object?>['reactx demo']), 
h('p', const <String, Object?>{}, <Object?>['React, reimplemented in Dart — server-rendered, then hydrated.']), 
CounterProps(), 
TodosProps()]
);

/// A classic counter.
Component Counter() {
  final (count, setCount) = useState(0);

  return h('section', <String, Object?>{'class': 'counter'}, <Object?>[
h('h2', const <String, Object?>{}, <Object?>['Counter']), 
h('p', const <String, Object?>{}, <Object?>['Value: ', h('strong', const <String, Object?>{}, <Object?>[count])]), 
h('button', <String, Object?>{'onClick': (() => setCount((c) => c - 1))}, <Object?>['-']), 
h('button', <String, Object?>{'onClick': (() => setCount((c) => c + 1))}, <Object?>['+'])]
);
}

/// A controlled-input todo list. Shows keyed list reconciliation.
Component Todos() {
  final (items, setItems) = useState<List<String>>(const ['Learn reactx']);
  final (draft, setDraft) = useState('');

  void add() {
    if (draft.trim().isEmpty) return;
    setItems([...items, draft.trim()]);
    setDraft('');
  }

  return h('section', <String, Object?>{'class': 'todos'}, <Object?>[
h('h2', const <String, Object?>{}, <Object?>['Todos (', items.length, ')']), 
h('ul', const <String, Object?>{}, <Object?>[
([for (final (i, item) in items.indexed) h('li', <String, Object?>{'key': i}, <Object?>[item])])]
), 
h('input', <String, Object?>{'value': draft, 'onInput': (onValue(setDraft)), 'placeholder': 'Add a todo'}, const <Object?>[]), 
h('button', <String, Object?>{'onClick': add}, <Object?>['Add'])]
);
}

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class AppProps extends ComponentProps {
  const AppProps({super.key});
  @override
  String get name => 'App';
  @override
  VNode build() => App();
}

final class CounterProps extends ComponentProps {
  const CounterProps({super.key});
  @override
  String get name => 'Counter';
  @override
  VNode build() => Counter();
}

final class TodosProps extends ComponentProps {
  const TodosProps({super.key});
  @override
  String get name => 'Todos';
  @override
  VNode build() => Todos();
}

// GENERATED by dartx from app.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
