// GENERATED by the reactx jsx precompiler. Do not edit.
// Precompiled from app.dart.
// ignore_for_file: type=lint

import 'package:reactx/reactx.dart';

/// Registers the precompiled jsx templates found in
/// [app.dart]. Call once before rendering.
void registerAppTemplates() {
  registerCompiledTemplate(
    '    <section class="counter">\n      <h2>Counter</h2>\n      <p>Value: <strong>\${0}</strong></p>\n      <button onClick=\${1}>-</button>\n      <button onClick=\${2}>+</button>\n    </section>\n  ',
    (List<Object?> args) => h('section', <String, Object?>{'class': 'counter'}, <Object?>[h('h2', <String, Object?>{}, <Object?>[TextNode('Counter')]), h('p', <String, Object?>{}, <Object?>[TextNode('Value: '), h('strong', <String, Object?>{}, <Object?>[args[0]])]), h('button', <String, Object?>{'onClick': args[1]}, <Object?>[TextNode('-')]), h('button', <String, Object?>{'onClick': args[2]}, <Object?>[TextNode('+')])]),
  );
  registerCompiledTemplate(
    '    <section class="todos">\n      <h2>Todos (\${0})</h2>\n      <ul>\${1}</ul>\n      <input value="\${2}" onInput=\${3} placeholder="Add a todo" />\n      <button onClick=\${4}>Add</button>\n    </section>\n  ',
    (List<Object?> args) => h('section', <String, Object?>{'class': 'todos'}, <Object?>[h('h2', <String, Object?>{}, <Object?>[TextNode('Todos ('), args[0], TextNode(')')]), h('ul', <String, Object?>{}, <Object?>[args[1]]), h('input', <String, Object?>{'value': args[2], 'onInput': args[3], 'placeholder': 'Add a todo'}, <Object?>[]), h('button', <String, Object?>{'onClick': args[4]}, <Object?>[TextNode('Add')])]),
  );
}
