/// Server-side rendering entrypoint.
///
/// Run it to print a full HTML document to stdout:
///
/// ```
/// dart run example/server.dart > index.html
/// ```
///
/// The emitted page references `main.dart.js` (compile `example/main.dart`),
/// which hydrates the same tree in the browser.
library;

import 'dart:io';

import 'package:reactx/reactx.dart';

import 'app.dart';
// Generated by `dart run build_runner build`. Warms the template cache so no
// jsx parsing happens at request time.
import 'app.reactx.g.dart';

void main() {
  registerAppTemplates();

  final html = renderToDocument(
    use(app),
    title: 'reactx demo',
    bootstrapScript: 'main.dart.js',
    head: '<style>'
        'body{font-family:system-ui,sans-serif;max-width:40rem;margin:2rem auto}'
        'section{border:1px solid #ddd;border-radius:8px;padding:1rem;margin:1rem 0}'
        'button{margin-right:.5rem}'
        '</style>',
  );

  stdout.write(html);
}
