/// What renders when a todo route's loader fails.
///
/// The router picks the nearest `errorComponent` at or above the failure and
/// stops descending, so this replaces the page that could not load rather than
/// appearing beside a half-drawn one. Try `/todo/999`.
library;

import 'package:reactx/reactx.dart';
import 'package:reactx/router.dart';

import '../../../data/todo_api.dart';

Component TodoErrorPage() {
  final error = useRouteError();

  // A missing todo is a different answer than a broken load, and the page says
  // so — which is exactly why the API throws a type rather than returning null.
  final missing = error is TodoNotFound;

  return h('article', <String, Object?>{'class': 'stack'}, <Object?>[
h('header', <String, Object?>{'class': 'page-head'}, <Object?>[
h('h1', const <String, Object?>{}, <Object?>[(missing ? 'No such todo' : 'That did not load')]), 
h('p', <String, Object?>{'class': 'lede'}, <Object?>[
(missing
            ? 'The URL names a todo that does not exist.'
            : 'The loader for this route threw.')]
)]
), 

h('pre', <String, Object?>{'class': 'error-detail'}, <Object?>[('$error')]), 

h('p', <String, Object?>{'class': 'row'}, <Object?>[
LinkProps(href: '/', className: 'btn primary', children: normalizeChildren(<Object?>['Back to the list']))]
)]
);
}

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class TodoErrorPageProps extends ComponentProps {
  const TodoErrorPageProps({super.key});
  @override
  String get name => 'TodoErrorPage';
  @override
  VNode build() => TodoErrorPage();
}

// GENERATED by dartx from error.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
