/// Anything the route table does not know.
///
/// The server pairs this page with a real 404 status (see `server.dart`), so an
/// unknown URL is a 404 to a crawler as well as to a reader.
library;

import 'package:reactx/reactx.dart';
import 'package:reactx/router.dart';

Component NotFoundPage() {
  final path = useRoutePath();

  return h('section', <String, Object?>{'class': 'stack'}, <Object?>[
h('header', <String, Object?>{'class': 'page-head'}, <Object?>[
h('h1', const <String, Object?>{}, <Object?>['404']), 
h('p', <String, Object?>{'class': 'lede'}, <Object?>['Nothing lives at ', h('code', const <String, Object?>{}, <Object?>[path]), '.'])]
), 
h('p', <String, Object?>{'class': 'hint'}, <Object?>[LinkProps(href: '/', className: 'nav-link', children: normalizeChildren(<Object?>['Back to the todos']))])]
);
}

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class NotFoundPageProps extends ComponentProps {
  const NotFoundPageProps({super.key});
  @override
  String get name => 'NotFoundPage';
  @override
  VNode build() => NotFoundPage();
}

// GENERATED by dartx from not_found_page.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
