/// Where `requireSignedIn` sends you.
///
/// The guard puts the page you were heading for in `?next=`, so signing in can
/// return you there instead of dumping you on the home page.
///
/// The two buttons are plain links to server endpoints, not client-side
/// handlers: setting a cookie is the server's job, and doing it this way keeps
/// the example free of browser-only code in shared components.
library;

import 'package:reactx/reactx.dart';
import 'package:reactx/router.dart';

import '../models/session.dart';

Component SignInPage() {
  final next = useQuery()['next'] ?? '/';
  final session = useRouteExtra<Session>();

  return h('article', <String, Object?>{'class': 'stack'}, <Object?>[
h('header', <String, Object?>{'class': 'page-head'}, <Object?>[
h('h1', const <String, Object?>{}, <Object?>['Sign in']), 
h('p', <String, Object?>{'class': 'lede'}, <Object?>['A guard sent you here because ', 
h('code', const <String, Object?>{}, <Object?>[next]), ' is protected.']
)]
), 

(session?.signedIn == true
        ? FragmentNode(normalizeChildren(<Object?>[
h('p', <String, Object?>{'class': 'note'}, <Object?>['You are signed in.']), 
h('p', <String, Object?>{'class': 'row'}, <Object?>[
LinkProps(href: next, className: 'btn primary', children: normalizeChildren(<Object?>['Continue'])), 
h('a', <String, Object?>{'class': 'btn ghost', 'href': '/signout'}, <Object?>['Sign out'])]
)]
))
        : h('p', <String, Object?>{'class': 'row'}, <Object?>[


h('a', <String, Object?>{'class': 'btn primary', 
'href': ('/session/in?next=${Uri.encodeComponent(next)}')}, <Object?>['Sign in as the demo user']

)]
)), 

h('p', <String, Object?>{'class': 'note'}, <Object?>['The session is a cookie the server reads per request and hands to the router as ', 

h('code', const <String, Object?>{}, <Object?>['extra']), ' — never a global, so two visitors never see each other\'s answer.']

)]
);
}

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class SignInPageProps extends ComponentProps {
  const SignInPageProps({super.key});
  @override
  String get name => 'SignInPage';
  @override
  VNode build() => SignInPage();
}

// GENERATED by dartx from sign_in_page.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
