/// Page 2 — numbers derived from the same store the list writes to.
///
/// Nothing is synchronised between the two pages, because there is nothing to
/// synchronise: both read one [TodoState], and the derived values are getters
/// on it. Tick a box on `/`, come back here, and the bars have already moved.
library;

import 'package:reactx/reactx.dart';
import 'package:reactx/router.dart';

import '../components/stat_card.dartx.dart';
import '../state/todo_store.dart';

Component StatsPage() {
  final (state, _) = useStore(todoStore);

  // Recomputed only when the todos actually change — navigating here, or a
  // filter change on the other page, reuses the previous map.
  final byTag = useMemo(() => state.byTag, [state.todos]);

  return h('section', <String, Object?>{'class': 'stack'}, <Object?>[
h('header', <String, Object?>{'class': 'page-head'}, <Object?>[
h('h1', const <String, Object?>{}, <Object?>['Stats']), 
h('p', <String, Object?>{'class': 'lede'}, <Object?>['Everything below is sadderived state — no second copy.'])]
), 

h('div', <String, Object?>{'class': 'cards'}, <Object?>[
StatCardProps(label: 'Total', value: state.todos.length), 
StatCardProps(label: 'Done', value: state.completed), 
StatCardProps(label: 'Remaining', value: state.remaining)]
), 

h('div', <String, Object?>{'class': 'progress-block'}, <Object?>[
h('div', <String, Object?>{'class': 'progress-head'}, <Object?>[
h('span', const <String, Object?>{}, <Object?>['Overall']), 
h('span', const <String, Object?>{}, <Object?>[state.percentDone, '%'])]
), 
h('div', <String, Object?>{'class': 'progress'}, <Object?>[
h('div', <String, Object?>{'class': 'progress-fill', 'style': ({'width': '${state.percentDone}%'})}, const <Object?>[])]
)]
), 

h('h2', const <String, Object?>{}, <Object?>['By tag']), 
(byTag.isEmpty
        ? h('p', <String, Object?>{'class': 'empty'}, <Object?>['No todos to break down.'])
        : h('ul', <String, Object?>{'class': 'bars'}, <Object?>[
([
              for (final entry in byTag.entries)
                h('li', <String, Object?>{'key': entry.key, 'class': 'bar-row'}, <Object?>[
h('span', <String, Object?>{'class': ('tag tag-${entry.key}')}, <Object?>[entry.key]), 
h('div', <String, Object?>{'class': 'progress'}, <Object?>[
h('div', <String, Object?>{
'class': 'progress-fill', 
'style': ({
                        'width':
                            '${(entry.value.done * 100 / entry.value.total).round()}%'
                      })}, const <Object?>[]
)]
), 
h('span', <String, Object?>{'class': 'bar-count'}, <Object?>[
entry.value.done, '/', entry.value.total]
)]
),
            ])]
)), 

h('p', <String, Object?>{'class': 'hint'}, <Object?>['Want to change these numbers? ', 
LinkProps(href: '/', className: 'nav-link', children: normalizeChildren(<Object?>['Back to the list'])
), '.']
)]
);
}

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class StatsPageProps extends ComponentProps {
  const StatsPageProps({super.key});
  @override
  String get name => 'StatsPage';
  @override
  VNode build() => StatsPage();
}

// GENERATED by dartx from stats_page.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
