/// `/todo/3/edit` — the panel behind the guard.
///
/// Two things this page does not do, both on purpose:
///
/// * It does not check whether you are allowed to be here. `requireSignedIn`
///   settled that before any loader ran and before this component existed,
///   which is the point of a guard — an unauthorised visitor never reaches the
///   code that would have to remember to check.
/// * It does not load the todo. Its *parent* route did, and a child can read an
///   ancestor's data: one fetch, two pages.
library;

import 'package:reactx/events.dart';
import 'package:reactx/reactx.dart';
import 'package:reactx/router.dart';

import '../models/todo.dart';
import '../routes.dart';

Component TodoEditPage() {
  final todo = useLoaderData<Todo>(todoDetailRoute);

  return h('section', <String, Object?>{'class': 'panel-edit'}, <Object?>[
h('h2', const <String, Object?>{}, <Object?>['Edit']), 

h('form', <String, Object?>{'class': 'todo-form', 'onSubmit': ((Object event) => preventDefault(event))}, <Object?>[
h('input', <String, Object?>{'class': 'input', 'value': todo.title, 'aria-label': 'Title'}, const <Object?>[]), 
h('button', <String, Object?>{'class': 'btn primary', 'type': 'submit'}, <Object?>['Save'])]
), 

h('p', <String, Object?>{'class': 'note'}, <Object?>['Deliberately inert — the example is about routing, not persistence. Note the URL: this panel is a real location, so it survives a reload and the Back button closes it.']



), 

h('p', <String, Object?>{'class': 'row'}, <Object?>[
LinkProps(href: ('/todo/${todo.id}'), className: 'btn ghost', replace: true, children: normalizeChildren(<Object?>['Close']))]
)]
);
}

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class TodoEditPageProps extends ComponentProps {
  const TodoEditPageProps({super.key});
  @override
  String get name => 'TodoEditPage';
  @override
  VNode build() => TodoEditPage();
}

// GENERATED by dartx from todo_edit_page.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
