/// One todo, addressed by URL: `/todo/3`.
///
/// The page never fetches anything. By the time it renders, its route's loader
/// has already run — on the server for the first paint, in the browser for a
/// client transition — so there is no loading branch here, no `useEffect`, and
/// nothing to get wrong about the order those two arrive in.
///
/// It is also a *parent* route: `/todo/3/edit` renders through the `<Outlet />`
/// at the bottom, below this page rather than instead of it. That is why the
/// edit form can read this route's todo without loading it again.
library;

import 'package:reactx/reactx.dart';
import 'package:reactx/router.dart';

import '../models/session.dart';
import '../models/todo.dart';
import '../routes.dart';

Component TodoDetailPage() {
  // Keyed by the route object, not by a name: rename `todoDetailRoute` and this
  // follows, and no other route can collide with it.
  final todo = useLoaderData<Todo>(todoDetailRoute);
  final session = useRouteExtra<Session>();

  return h('article', <String, Object?>{'class': 'stack'}, <Object?>[
h('header', <String, Object?>{'class': 'page-head'}, <Object?>[
h('h1', const <String, Object?>{}, <Object?>[todo.title]), 
h('p', <String, Object?>{'class': 'lede'}, <Object?>['Loaded by this route\'s loader, before the page rendered.']

)]
), 

h('dl', <String, Object?>{'class': 'detail'}, <Object?>[
h('dt', const <String, Object?>{}, <Object?>['Status']), 
h('dd', const <String, Object?>{}, <Object?>[(todo.done ? 'Done' : 'Still to do')]), 
h('dt', const <String, Object?>{}, <Object?>['Tag']), 
h('dd', const <String, Object?>{}, <Object?>[h('span', <String, Object?>{'class': ('tag tag-${todo.tag}')}, <Object?>[todo.tag])]), 
h('dt', const <String, Object?>{}, <Object?>['Id']), 
h('dd', const <String, Object?>{}, <Object?>[todo.id])]
), 

h('p', <String, Object?>{'class': 'row'}, <Object?>[
LinkProps(href: ('/todo/${todo.id}/edit'), className: 'btn primary', children: normalizeChildren(<Object?>['Edit'])), 
LinkProps(href: '/', className: 'btn ghost', children: normalizeChildren(<Object?>['Back to the list']))]
), 

(session?.signedIn == true
        ? h('p', <String, Object?>{'class': 'note'}, <Object?>['You are signed in, so Edit will open below.'])
        : h('p', <String, Object?>{'class': 'note'}, <Object?>['Edit is guarded — it will send you to the sign-in page.']

)), 


OutletProps()]
);
}

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class TodoDetailPageProps extends ComponentProps {
  const TodoDetailPageProps({super.key});
  @override
  String get name => 'TodoDetailPage';
  @override
  VNode build() => TodoDetailPage();
}

// GENERATED by dartx from todo_detail_page.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
