/// A build_runner [Builder] that precompiles `jsx(r'...')` templates.
///
/// For every source file that calls `jsx` with a **raw string literal**, it
/// emits a `<name>.reactx.g.dart` file containing a `register…Templates()`
/// function. Calling that function once at startup fills the runtime template
/// cache with directly-constructed builders, so those templates never hit the
/// runtime parser. It's the Babel-for-JSX step, made optional: without it the
/// same templates still work, just parsed lazily on first use.
library;

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import 'package:build/build.dart';

import '../jsx.dart';
import 'emitter.dart';

/// Builder factory referenced from `build.yaml`.
Builder reactxJsxBuilder(BuilderOptions options) => JsxPrecompileBuilder();

class JsxPrecompileBuilder implements Builder {
  @override
  Map<String, List<String>> get buildExtensions => const {
        '.dart': ['.reactx.g.dart'],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final input = buildStep.inputId;
    if (input.path.endsWith('.reactx.g.dart')) return;

    final content = await buildStep.readAsString(input);
    final parsed = parseString(content: content, throwIfDiagnostics: false);

    final finder = _JsxFinder();
    parsed.unit.accept(finder);
    if (finder.templates.isEmpty) return;

    final fileName = input.pathSegments.last;
    final out = StringBuffer()
      ..writeln('// GENERATED by the reactx jsx precompiler. Do not edit.')
      ..writeln('// Precompiled from $fileName.')
      ..writeln('// ignore_for_file: type=lint')
      ..writeln()
      ..writeln("import 'package:reactx/reactx.dart';")
      ..writeln()
      ..writeln('/// Registers the precompiled jsx templates found in')
      ..writeln('/// [$fileName]. Call once before rendering.')
      ..writeln('void ${_registerName(fileName)}() {');

    for (final template in finder.templates) {
      final expr = emitTemplate(parseTemplate(template));
      out
        ..writeln('  registerCompiledTemplate(')
        ..writeln('    ${_str(template)},')
        ..writeln('    $expr,')
        ..writeln('  );');
    }

    out.writeln('}');
    await buildStep.writeAsString(
        input.changeExtension('.reactx.g.dart'), out.toString());
  }
}

/// Collects the raw-string templates passed to `jsx(...)`.
class _JsxFinder extends RecursiveAstVisitor<void> {
  final List<String> templates = [];

  @override
  void visitMethodInvocation(MethodInvocation node) {
    if (node.methodName.name == 'jsx' &&
        node.argumentList.arguments.isNotEmpty) {
      final first = node.argumentList.arguments.first;
      if (first is SimpleStringLiteral && first.isRaw) {
        templates.add(first.value);
      }
    }
    super.visitMethodInvocation(node);
  }
}

String _registerName(String fileName) {
  final base = fileName.replaceAll(RegExp(r'\.dart$'), '');
  final camel = base
      .split(RegExp('[^A-Za-z0-9]+'))
      .where((s) => s.isNotEmpty)
      .map((s) => s[0].toUpperCase() + s.substring(1))
      .join();
  return 'register${camel}Templates';
}

String _str(String s) {
  final escaped = s
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r')
      .replaceAll('\t', r'\t');
  return "'$escaped'";
}
