/// The dartx transpiler: `.dartx` source in, plain Dart out.
///
/// dartx is a **preprocessor**, not a Dart parser. It streams the file through
/// untouched — every import, class, comment and string exactly as written — and
/// only takes over when it finds markup in expression position. That is why a
/// `.dartx` file is just a Dart file with `<div>` allowed inside it, and why
/// anything Dart can express keeps working.
///
/// Two properties are worth knowing about the output:
///
///   * **Line numbers are preserved.** Markup is emitted on a single line and
///     padded with the newlines it consumed, so line *N* of the generated
///     `.dart` is line *N* of the `.dartx`. Analyzer errors, stack traces and
///     breakpoints all land on the right line.
///   * **The banner is at the bottom**, for the same reason.
library;

import 'diagnostics.dart';
import 'emitter.dart';
import 'parser.dart';
import 'props.dart';
import 'scanner.dart';

/// The outcome of transpiling one file.
class DartxResult {
  /// Generated Dart source, or `null` when [errors] is non-empty.
  final String? code;

  /// Diagnostics, positioned in the original `.dartx` source.
  final List<DartxError> errors;

  const DartxResult({this.code, this.errors = const []});

  bool get ok => code != null;
}

/// Transpiles [source] (the contents of a `.dartx` file) into Dart.
///
/// [uri] is used only to label diagnostics and the generated banner.
/// Set [props] to false to skip generating props types — useful when you only
/// want the markup compiled, as the emitter's own tests do.
DartxResult transpileDartx(String source,
    {String? uri, bool banner = true, bool props = true}) {
  try {
    final transpiler = _Transpiler(source);
    var code = transpiler.run(0, source.length);
    // Appended, not woven in, so every line above keeps the number it had in
    // the .dartx file.
    if (props) code += generatePropsClasses(code);
    return DartxResult(
      code: banner ? '$code${_banner(uri)}' : code,
    );
  } on DartxError catch (e) {
    return DartxResult(errors: [e.withUri(uri)]);
  }
}

String _banner(String? uri) {
  final from = uri == null ? '' : ' from ${_basename(uri)}';
  return '\n'
      '// GENERATED by dartx$from — do not edit.\n'
      '// Line numbers match the .dartx source, which is why this banner is at\n'
      '// the bottom of the file rather than the top.\n'
      '// ignore_for_file: type=lint\n';
}

String _basename(String path) => path.split(RegExp(r'[/\\]')).last;

class _Transpiler {
  final String source;
  final LineMap lineMap;

  _Transpiler(this.source) : lineMap = LineMap(source);

  /// Transpiles `[start, end)` of [source].
  String run(int start, int end) {
    final out = StringBuffer();
    var i = start;

    /// Index of the last significant (non-whitespace, non-comment) character
    /// copied through, or `-1` at the start of this range. Deciding whether a
    /// `<` opens markup needs exactly this and nothing more.
    var prevSignificant = -1;

    while (i < end) {
      final c = source.codeUnitAt(i);

      if (c == 0x2f && i + 1 < end) {
        final n = source.codeUnitAt(i + 1);
        if (n == 0x2f) {
          i = _copy(out, i, skipLineComment(source, i), end);
          continue;
        }
        if (n == 0x2a) {
          i = _copy(out, i, skipBlockComment(source, i), end);
          continue;
        }
      }

      if (isStringStart(source, i)) {
        final stop = _copyString(out, i, end);
        prevSignificant = stop - 1;
        i = stop;
        continue;
      }

      if (c == 0x3c && _startsMarkup(i, prevSignificant, end)) {
        final parser = DartxParser(
          source,
          lineMap: lineMap,
          transpileEmbedded: run,
          start: i,
        );
        final element = parser.parseElement();
        final consumedTo = parser.i;
        final emitted = emitElement(element, lineMap: lineMap);
        out.write(emitted);
        out.write(_padding(i, consumedTo, emitted));
        prevSignificant = consumedTo - 1;
        i = consumedTo;
        continue;
      }

      out.writeCharCode(c);
      if (!isWhitespace(c)) prevSignificant = i;
      i++;
    }

    return out.toString();
  }

  /// Copies a string literal, transpiling any markup inside its `\${…}`
  /// interpolations.
  ///
  /// The literal itself is text and must be copied through untouched, but an
  /// interpolation is ordinary Dart in expression position — `'x \${<b>ok</b>}'`
  /// is a real thing to write, and copying it verbatim leaves markup in the
  /// output with no diagnostic.
  int _copyString(StringBuffer out, int from, int limit) {
    final stop = skipStringLiteral(source, from);
    final end = stop < limit ? stop : limit;

    // A raw string has no interpolations to look at.
    if (source.codeUnitAt(from) == 0x72) {
      out.write(source.substring(from, end));
      return end > from ? end : from + 1;
    }

    var i = from;
    while (i < end) {
      if (source.codeUnitAt(i) == 0x5c) {
        // An escape: both characters belong to the literal.
        out.write(source.substring(i, (i + 2) < end ? i + 2 : end));
        i += 2;
        continue;
      }
      if (source.startsWith(r'${', i)) {
        final close = skipBalancedBraces(source, i + 1);
        if (close < 0 || close > end) break; // malformed; copy the rest as-is
        out.write(r'${');
        out.write(run(i + 2, close - 1));
        out.write('}');
        i = close;
        continue;
      }
      out.writeCharCode(source.codeUnitAt(i));
      i++;
    }
    if (i < end) out.write(source.substring(i, end));
    return end > from ? end : from + 1;
  }

  /// Copies `[from, min(to, limit))` verbatim and returns the new index.
  int _copy(StringBuffer out, int from, int to, int limit) {
    final stop = to < limit ? to : limit;
    out.write(source.substring(from, stop));
    // A zero-width step would spin forever; never happens for well-formed
    // comments and strings, but the loop above must always make progress.
    return stop > from ? stop : from + 1;
  }

  /// A safety net for the emitter's line accounting: if for any reason it
  /// produced fewer newlines than the markup spanned, make up the difference so
  /// the rest of the file keeps its line numbers. In practice this is empty.
  String _padding(int from, int to, String emitted) {
    final consumed = _countNewlines(source, from, to);
    final produced = _countNewlines(emitted, 0, emitted.length);
    final missing = consumed - produced;
    return missing > 0 ? '\n' * missing : '';
  }

  static int _countNewlines(String s, int from, int to) {
    var n = 0;
    for (var i = from; i < to; i++) {
      if (s.codeUnitAt(i) == 0x0a) n++;
    }
    return n;
  }

  /// Decides whether the `<` at [lt] opens markup.
  ///
  /// Three things have to line up: something can syntactically start there, it
  /// looks like a tag, and it is not one of Dart's own angle brackets.
  bool _startsMarkup(int lt, int prevSignificant, int end) {
    if (lt + 1 >= end) return false;
    final next = source.codeUnitAt(lt + 1);
    if (next == 0x3e) return true; // `<>` is never valid Dart
    if (!isIdentifierStart(next)) return false;
    if (!isExpressionPosition(source, prevSignificant)) return false;
    if (looksLikeTypeArguments(source, lt)) return false;
    return true;
  }
}
