/// Page 1 — the list itself.
///
/// A page is just a component. It takes no props: everything it needs comes
/// from the store, and the route that selected it is the router's business.
library;

import 'package:reactx/events.dart';
import 'package:reactx/reactx.dart';

import '../components/filter_bar.dartx.dart';
import '../components/todo_form.dartx.dart';
import '../components/todo_item.dartx.dart';
import '../models/todo.dart';
import '../routes.dart';
import '../state/todo_store.dart';

Component TodosPage() {
  final (state, dispatch) = useStore(todoStore);
  final visible = state.visible;

  return h('section', <String, Object?>{'class': 'stack'}, <Object?>[
h('header', <String, Object?>{'class': 'page-head'}, <Object?>[
h('h1', const <String, Object?>{}, <Object?>['Todos']), 
h('p', <String, Object?>{'class': 'lede'}, <Object?>[
state.remaining, ' of ', state.todos.length, ' still to do. Add, tick and filter — then open Stats and watch the same numbers move.']

)]
), 

TodoFormProps(), 
FilterBarProps(), 

(visible.isEmpty
        ? h('p', <String, Object?>{'class': 'empty'}, <Object?>[
(state.filter == Filter.all
                ? 'Nothing here yet. Add your first todo above.'
                : 'No ${state.filter.label.toLowerCase()} todos.')]
)
        : h('ul', <String, Object?>{'class': 'todo-list'}, <Object?>[
([for (final todo in visible) TodoItemProps(key: todo.id, todo: todo)])]
)), 

(state.completed == 0
        ? null
        : h('button', <String, Object?>{
'class': 'btn ghost', 
'type': 'button', 
'onClick': (on(() => dispatch(const ClearDone())))}, <Object?>[
'Clear ', 
state.completed, ' completed']
))]
);
}

/// Picked up by the generator and hung off this route's `title`.
const title = PageInfo('Todos · reactx', 'A todo list rendered on the server, then hydrated.');

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class TodosPageProps extends ComponentProps {
  const TodosPageProps({super.key});
  @override
  String get name => 'TodosPage';
  @override
  VNode build() => TodosPage();
}

// GENERATED by dartx from page.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
