/// The All / Active / Done chips.
///
/// The filter lives in the store rather than in this component, so it survives
/// navigating to another page and back.
library;

import 'package:reactx/events.dart';
import 'package:reactx/reactx.dart';

import '../models/todo.dart';
import '../state/todo_store.dart';

Component FilterBar() {
  // Only the selected filter matters here, so adding or ticking a todo does
  // not re-render the chips.
  final selected = useSelect(todoStore, (s) => s.filter);
  final dispatch = useDispatch(todoStore);

  // `aria-pressed` takes the *string* "true"/"false"; a bare boolean attribute
  // would mean something else, so it is spelled out below.
  return h('div', <String, Object?>{'class': 'filters', 'role': 'group', 'aria-label': 'Filter todos'}, <Object?>[
([
      for (final filter in Filter.values)
        h('button', <String, Object?>{
'key': filter.name, 
'type': 'button', 
'class': (filter == selected ? 'chip is-on' : 'chip'), 
'aria-pressed': (filter == selected ? 'true' : 'false'), 
'onClick': (on(() => dispatch(SetFilter(filter))))}, <Object?>[

filter.label]
),
    ])]
);
}

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class FilterBarProps extends ComponentProps {
  const FilterBarProps({super.key});
  @override
  String get name => 'FilterBar';
  @override
  VNode build() => FilterBar();
}

// GENERATED by dartx from filter_bar.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
