/// The chrome every page shares: header, navigation, footer.
///
/// [Layout] is the *root route*, not a wrapper someone remembered to wrap the
/// pages in. The page it frames arrives through `<Outlet />` — whichever child
/// route matched, already loaded — so the layout knows nothing about routing
/// beyond its links, and adding a page cannot forget the chrome.
///
/// Two small things earn their keep here:
///
/// * The badge uses `useSelect`, so it re-renders when the *number* of
///   unfinished todos changes and not when anything else in the store moves —
///   switching the filter on the list page leaves it alone.
/// * The progress bar uses `useNavigation`. Client navigations run loaders
///   before they commit, so a slow route would otherwise look like a dead
///   click; this is the router telling the UI it is working.
library;

import 'package:reactx/reactx.dart';
import 'package:reactx/router.dart';

import '../models/session.dart';
import '../state/todo_store.dart';

Component Layout() {
  final remaining = useSelect(todoStore, (s) => s.remaining);
  final navigation = useNavigation();
  final session = useRouteExtra<Session>();

  return FragmentNode(normalizeChildren(<Object?>[
h('header', <String, Object?>{'class': 'site-head'}, <Object?>[



h('a', <String, Object?>{'class': 'brand', 'href': '/'}, <Object?>[
h('span', <String, Object?>{'class': 'brand-mark'}, <Object?>['✓']), 
h('span', const <String, Object?>{}, <Object?>['reactx todos'])]
), 
h('nav', <String, Object?>{'class': 'nav', 'aria-label': 'Main'}, <Object?>[
LinkProps(href: '/', className: 'nav-link', activeClass: 'is-active', children: normalizeChildren(<Object?>['Todos'])), 


LinkProps(href: '/todo/2', className: 'nav-link', activeClass: 'is-active', 
exact: false, children: normalizeChildren(<Object?>['Todo'])), 
LinkProps(href: '/stats', className: 'nav-link', activeClass: 'is-active', children: normalizeChildren(<Object?>['Stats'])), 
LinkProps(href: '/about', className: 'nav-link', activeClass: 'is-active', children: normalizeChildren(<Object?>['About']))]
), 
h('span', <String, Object?>{'class': 'badge', 'title': 'Todos still to do'}, <Object?>[remaining, ' left'])]
), 


h('div', <String, Object?>{
'class': (navigation.isLoading ? 'route-progress is-loading' : 'route-progress'), 
'role': 'status', 
'aria-live': 'polite'}, <Object?>[

h('span', <String, Object?>{'class': 'visually-hidden'}, <Object?>[
(navigation.isLoading ? 'Loading ${navigation.location}' : '')]
)]
), 

h('main', <String, Object?>{'class': 'page'}, <Object?>[OutletProps()]), 

h('footer', <String, Object?>{'class': 'site-foot'}, <Object?>[
h('span', const <String, Object?>{}, <Object?>['Five routes, one component tree — server-rendered in Dart, then hydrated.']


), 
(session?.signedIn == true
          ? h('a', <String, Object?>{'class': 'foot-link', 'href': '/signout'}, <Object?>['Sign out'])
          : LinkProps(href: '/signin', className: 'foot-link', children: normalizeChildren(<Object?>['Sign in'])))]
)]
));
}

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class LayoutProps extends ComponentProps {
  const LayoutProps({super.key});
  @override
  String get name => 'Layout';
  @override
  VNode build() => Layout();
}

// GENERATED by dartx from layout.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
