/// A labelled number. The smallest thing in the app that takes arguments —
/// and the clearest look at what a `Component` return type buys.
///
/// The parameters below are the attributes: `<StatCard label="Done" value={3}/>`
/// compiles to `StatCardProps(label: 'Done', value: 3)`, so a misspelled
/// `lable` or a `String` where the `int` goes is a compile error on the line
/// that wrote it. Nothing here reads a map, and nothing casts.
library;

import 'package:reactx/reactx.dart';

Component StatCard({required String label, required int value}) => h('div', <String, Object?>{'class': 'card'}, <Object?>[
h('div', <String, Object?>{'class': 'card-value'}, <Object?>[value]), 
h('div', <String, Object?>{'class': 'card-label'}, <Object?>[label])]
);

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class StatCardProps extends ComponentProps {
  const StatCardProps({required this.label, required this.value, super.key});
  final String label;
  final int value;
  @override
  String get name => 'StatCard';
  @override
  VNode build() => StatCard(label: label, value: value);
  @override
  List<Object?> get fields => [label, value];
}

// GENERATED by dartx from stat_card.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
