/// The "add a todo" form: a controlled input, a tag `<select>`, and a submit.
library;

import 'package:reactx/events.dart';
import 'package:reactx/reactx.dart';

import '../models/todo.dart';
import '../state/todo_store.dart';

Component TodoForm() {
  // The form writes but never reads, so it does not subscribe at all.
  final dispatch = useDispatch(todoStore);
  final (title, setTitle) = useState('');
  final (tag, setTag) = useState(tags.first);

  // Submitting is a form event, not a button click, so pressing Enter in the
  // input adds a todo too. `preventDefault` keeps the browser from navigating.
  void submit(Object event) {
    preventDefault(event);
    final text = title.trim();
    if (text.isEmpty) return;
    dispatch(AddTodo(text, tag));
    setTitle('');
  }

  return h('form', <String, Object?>{'class': 'todo-form', 'onSubmit': submit}, <Object?>[
h('input', <String, Object?>{
'class': 'input', 
'value': title, 
'placeholder': 'What needs doing?', 
'aria-label': 'Todo title', 
'autocomplete': 'off', 
'onInput': (onValue(setTitle))}, const <Object?>[]
), 
h('select', <String, Object?>{'class': 'select', 'aria-label': 'Tag', 'onChange': (onValue(setTag))}, <Object?>[
([
        for (final t in tags)
          h('option', <String, Object?>{'key': t, 'value': t, 'selected': (t == tag)}, <Object?>[t]),
      ])]
), 
h('button', <String, Object?>{'class': 'btn primary', 'type': 'submit', 'disabled': (title.trim().isEmpty)}, <Object?>['Add']

)]
);
}

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class TodoFormProps extends ComponentProps {
  const TodoFormProps({super.key});
  @override
  String get name => 'TodoForm';
  @override
  VNode build() => TodoForm();
}

// GENERATED by dartx from todo_form.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
