/// One row of the list.
///
/// Two things make it cheap. It takes its todo as an argument and gets the
/// dispatcher with `useDispatch`, which never subscribes — so ticking row 3
/// does not re-render rows 1, 2 and 4. And `@memoized` compares the arguments
/// field by field, so even the parent's re-render skips a row whose todo has
/// not changed.
library;

import 'package:reactx/events.dart';
import 'package:reactx/reactx.dart';

import '../models/todo.dart';
import '../state/todo_store.dart';

/// A row only re-renders when its own `todo` changes identity — and `Todo` is
/// immutable, so "changed" means exactly what you would expect.
@memoized
Component TodoItem({required Todo todo}) {
  final dispatch = useDispatch(todoStore);

  return h('li', <String, Object?>{'class': (todo.done ? 'todo is-done' : 'todo')}, <Object?>[
h('label', <String, Object?>{'class': 'todo-main'}, <Object?>[
h('input', <String, Object?>{
'type': 'checkbox', 
'checked': todo.done, 
'onChange': (on(() => dispatch(ToggleTodo(todo.id))))}, const <Object?>[]
), 
h('span', <String, Object?>{'class': 'todo-title'}, <Object?>[todo.title])]
), 
h('span', <String, Object?>{'class': ('tag tag-${todo.tag}')}, <Object?>[todo.tag]), 
h('button', <String, Object?>{
'class': 'btn ghost icon', 
'type': 'button', 
'aria-label': ('Delete ${todo.title}'), 
'onClick': (on(() => dispatch(RemoveTodo(todo.id))))}, <Object?>[
'×']

)]
);
}


// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class TodoItemProps extends ComponentProps {
  const TodoItemProps({required this.todo, super.key});
  final Todo todo;
  @override
  String get name => 'TodoItem';
  @override
  VNode build() => TodoItem(todo: todo);
  @override
  List<Object?> get fields => [todo];
  @override
  bool get memoized => true;
}

// GENERATED by dartx from todo_item.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
