/// Page 3 — what this app is, and how the pieces fit.
///
/// Almost entirely static markup, which is the point: a page that needs no
/// state is a plain function returning a tree, and it costs nothing at runtime.
library;

import 'package:reactx/reactx.dart';
import 'package:reactx/router.dart';
import '../../routes.dart';

/// Kept as a Dart string so the indentation survives exactly as written.
const _tree = '''
example/todo_app/
  server.dart              renders any route to HTML, serves the client bundle
  main.dart                hydrates the same tree in the browser
  src/
    app.dartx              router + store + layout + route outlet
    routes.dart            path -> page, title, description
    models/todo.dart       Todo, Filter, seed data (no framework imports)
    state/todo_store.dart  actions, reducer, context, useTodos()
    router/                useState + useEffect + context = a router
    components/            NavLink, Layout, TodoForm, TodoItem, FilterBar
    pages/                 one component per route
    styles.dart            the stylesheet, shared by every rendered page''';

Component AboutPage() => h('section', <String, Object?>{'class': 'stack'}, <Object?>[
h('header', <String, Object?>{'class': 'page-head'}, <Object?>[
h('h1', const <String, Object?>{}, <Object?>['About']), 
h('p', <String, Object?>{'class': 'lede'}, <Object?>['A three-page app in pure Dart: no JavaScript framework, no canvas, no template strings.']


)]
), 

h('h2', const <String, Object?>{}, <Object?>['How a request is served']), 
h('ol', <String, Object?>{'class': 'steps'}, <Object?>[
h('li', const <String, Object?>{}, <Object?>[
h('strong', const <String, Object?>{}, <Object?>['Server.']), ' The request path becomes a prop.', 
h('code', const <String, Object?>{}, <Object?>['renderToDocument']), ' runs the same components you see here and returns HTML — so this page is readable with JavaScript off, and by a crawler.']


), 
h('li', const <String, Object?>{}, <Object?>[
h('strong', const <String, Object?>{}, <Object?>['Client.']), ' ', h('code', const <String, Object?>{}, <Object?>['hydrateApp']), ' adopts that markup instead of rebuilding it, and the page becomes interactive without a flash.']


), 
h('li', const <String, Object?>{}, <Object?>[
h('strong', const <String, Object?>{}, <Object?>['Navigation.']), ' A ', h('code', const <String, Object?>{}, <Object?>['NavLink']), ' click is intercepted, the path goes into state, and only the page component swaps. The header, the store and the scroll position stay put.']


)]
), 

h('h2', const <String, Object?>{}, <Object?>['Why the state lives where it does']), 
h('p', const <String, Object?>{}, <Object?>['The store is mounted ', 
h('em', const <String, Object?>{}, <Object?>['above']), ' the route outlet, so pages unmount on navigation but the todos do not. Nothing is passed page-to-page: every component that needs the list calls ', 

h('code', const <String, Object?>{}, <Object?>['useTodos()']), ', and the header badge, the list and the charts are three readings of one value.']


), 

h('h2', const <String, Object?>{}, <Object?>['Layout']), 
h('pre', <String, Object?>{'class': 'tree'}, <Object?>[_tree]), 

h('p', <String, Object?>{'class': 'hint'}, <Object?>['Ready to look at it? ', 
LinkProps(href: '/', className: 'nav-link', children: normalizeChildren(<Object?>['Open the list'])
), ' or ', LinkProps(href: '/stats', className: 'nav-link', children: normalizeChildren(<Object?>['check the numbers'])
), '.']
)]
);

/// Picked up by the generator and hung off this route's `title`.
const title = PageInfo('About · reactx', 'How this Dart app is put together.');

// ---------------------------------------------------------------------
// Props types, generated from the Component functions above. Each one is
// what its markup call sites construct, which is why a misspelled or
// mistyped attribute is a compile error where you wrote it.
// ---------------------------------------------------------------------

final class AboutPageProps extends ComponentProps {
  const AboutPageProps({super.key});
  @override
  String get name => 'AboutPage';
  @override
  VNode build() => AboutPage();
}

// GENERATED by dartx from page.dartx — do not edit.
// Line numbers match the .dartx source, which is why this banner is at
// the bottom of the file rather than the top.
// ignore_for_file: type=lint
