// GENERATED by the reactx jsx precompiler. Do not edit.
// Precompiled from jsx_fixture.dart.
// ignore_for_file: type=lint

import 'package:reactx/reactx.dart';

/// Registers the precompiled jsx templates found in
/// [jsx_fixture.dart]. Call once before rendering.
void registerJsxFixtureTemplates() {
  registerCompiledTemplate(
    '    <section class="counter">\n      <h2>Counter</h2>\n      <p>Value: <strong>\${0}</strong></p>\n      <button onClick=\${1}>-</button>\n      <button onClick=\${2}>+</button>\n    </section>\n  ',
    (List<Object?> args) => h('section', <String, Object?>{'class': 'counter'}, <Object?>[h('h2', <String, Object?>{}, <Object?>[TextNode('Counter')]), h('p', <String, Object?>{}, <Object?>[TextNode('Value: '), h('strong', <String, Object?>{}, <Object?>[args[0]])]), h('button', <String, Object?>{'onClick': args[1]}, <Object?>[TextNode('-')]), h('button', <String, Object?>{'onClick': args[2]}, <Object?>[TextNode('+')])]),
  );
}
